[package]
name = "mlb-statics"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
test = false
doctest = false

[dependencies]
sml-lex = { path = "../sml-lex" }
sml-parse = { path = "../sml-parse" }
sml-lower = { path = "../sml-lower" }
sml-ty-var-scope = { path = "../sml-ty-var-scope" }
sml-statics = { path = "../sml-statics" }
sml-syntax = { path = "../sml-syntax" }
sml-hir = { path = "../sml-hir" }
mlb-hir = { path = "../mlb-hir" }
paths = { path = "../paths" }
text-size-util = { path = "../text-size-util" }
fast-hash = { path = "../fast-hash" }
sml-libs = { path = "../sml-libs" }
config = { path = "../config" }
text-pos = { git = "https://github.com/azdavis/language-util.git" }
