[package]
name = "analysis"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
test = false
doctest = false

[dependencies]
log = "0.4"
toml = "0.5"
topo-sort =  { git = "https://github.com/azdavis/language-util.git" }
text-pos = { git = "https://github.com/azdavis/language-util.git" }
config = { path = "../config" }
statics = { path = "../statics" }
syntax = { path = "../syntax" }
hir = { path = "../hir" }
paths = { path = "../paths" }
cm = { path = "../cm" }
mlb-syntax = { path = "../mlb-syntax" }
mlb-hir = { path = "../mlb-hir" }
mlb-statics = { path = "../mlb-statics" }
text-size-util = { path = "../text-size-util" }
elapsed = { path = "../elapsed" }
fast-hash = { path = "../fast-hash" }
fmt-util = { path = "../fmt-util" }
str-util = { path = "../str-util" }
