[package]
name = "analysis"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
test = false
doctest = false

[dependencies]
log = "0.4"
topo-sort =  { git = "https://github.com/azdavis/language-util.git" }
text-pos = { git = "https://github.com/azdavis/language-util.git" }
lex = { path = "../lex" }
parse = { path = "../parse" }
lower = { path = "../lower" }
ty-var-scope = { path = "../ty-var-scope" }
statics = { path = "../statics" }
syntax = { path = "../syntax" }
paths = { path = "../paths" }
cm = { path = "../cm" }
elapsed = { path = "../elapsed" }
fast-hash = { path = "../fast-hash" }
