[package]
name = "mlb-hir"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
test = false
doctest = false

[dependencies]
paths = { path = "../paths" }
sml-hir = { path = "../sml-hir" }
text-size-util = { path = "../text-size-util" }
