[package]
name = "lex-old"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
test = false
doctest = false

[dependencies]
intern = { path = "../intern" }
loc = { path = "../loc" }
token = { path = "../token" }
