[workspace]
members = ["crates/*", "xtask"]
resolver = "2"

[profile.release]
codegen-units = 1
lto = "fat"
strip = "symbols"

[profile.release-debug]
inherits = "release"
strip = "none"
debug = true
