[package]
name = "mlb-ast"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
doctest = false

[dependencies]
smol_str = "0.1"
path-slash = "0.1"
util = { path = "../util" }
located = { path = "../located" }
