[package]
name = "sml-statics"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
test = false
doctest = false

[dependencies]
config = { path = "../config" }
diagnostic-util = { path = "../diagnostic-util" }
drop_bomb = "0.1"
fast-hash = { path = "../fast-hash" }
fmt-util = { path = "../fmt-util" }
paths = { path = "../paths" }
pattern-match = { git = "https://github.com/azdavis/language-util.git" }
sml-hir = { path = "../sml-hir" }
str-util = { path = "../str-util" }
uniq = { git = "https://github.com/azdavis/language-util.git" }
