[package]
name = "lower"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
doctest = false
test = false

[dependencies]
hir = { path = "../hir" }
syntax = { path = "../syntax" }
fast-hash = { path = "../fast-hash" }
