[package]
name = "lower"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
doctest = false
test = false

[dependencies]
rustc-hash = "1"
hir = { path = "../hir" }
syntax = { path = "../syntax" }
