[package]
name = "millet-cli"
version = "0.1.0"
authors = ["Ariel Davis <ariel.z.davis@icloud.com>"]
edition = "2018"
publish = false

[[bin]]
name = "millet"
path = "src/main.rs"

[dependencies]
gumdrop = "0.8.0"
codespan-reporting = "0.9.4"
millet-core = { path = "../core" }
