[package]
name = "cli"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
pico-args = "0.5"
analysis = { path = "../analysis"}
config = { path = "../config"}
paths = { path = "../paths"}
