[package]
name = "millet-cli"
version = "0.1.0"
edition = "2018"
publish = false

[[bin]]
name = "millet"
path = "src/main.rs"

[dependencies]
codespan-reporting = "0.9"
millet-core = { path = "../core" }
pico-args = "0.3"
