[package]
name = "cli"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
codespan-reporting = "0.11"
pico-args = "0.4"
intern = { path = "../intern" }
lex-old = { path = "../lex-old" }
parse-old = { path = "../parse-old" }
statics = { path = "../statics" }
