[package]
name = "lang-srv"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1"
crossbeam-channel = "0.5"
log = "0.4"
lsp-server = "0.6"
lsp-types = "0.93"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
simple_logger = { version = "2", features = ["stderr"] }
analysis = { path = "../analysis" }
config = { path = "../config" }
paths = { path = "../paths" }
elapsed = { path = "../elapsed" }
fast-hash = { path = "../fast-hash" }
