[package]
name = "lang-srv"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
crossbeam-channel = "0.5"
lsp-types = "0.93"
base = { path = "../base" }
intern = { path = "../intern" }
serde = "1"
serde_json = "1"
