[package]
name = "lang-srv"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1"
lsp-server = "0.6"
lsp-types = "0.93"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
text-pos = { git = "https://github.com/azdavis/language-util.git" }
analysis = { path = "../analysis" }
