[package]
name = "statics"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
test = false
doctest = false

[dependencies]
pattern-match = { git = "https://github.com/azdavis/language-util.git" }
hir = { path = "../hir" }
fast-hash = { path = "../fast-hash" }
uniq = { git = "https://github.com/azdavis/language-util.git" }
