[package]
name = "statics"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
doctest = false

[dependencies]
rustc-hash = "1"
intern = { path = "../intern" }
token = { path = "../token" }
util = { path = "../util" }
loc = { path = "../loc" }
ast = { path = "../ast" }
