[package]
name = "statics"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
test = false
doctest = false

[dependencies]
log = "0.4"
drop_bomb = "0.1"
pattern-match = { git = "https://github.com/azdavis/language-util.git" }
uniq = { git = "https://github.com/azdavis/language-util.git" }
hir = { path = "../hir" }
paths = { path = "../paths" }
fast-hash = { path = "../fast-hash" }
