[package]
name = "old-lex"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
doctest = false

[dependencies]
old-intern = { path = "../old-intern" }
old-loc = { path = "../old-loc" }
old-token = { path = "../old-token" }
