[package]
name = "mlb-syntax"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
doctest = false

[dependencies]
lex-util = { path = "../lex-util" }
str-util = { path = "../str-util" }
text-size-util = { path = "../text-size-util" }
paths = { path = "../paths" }
