[package]
name = "mlb-syntax"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[lib]
test = false
doctest = false

[dependencies]
lex-util = { path = "../lex-util" }
paths = { path = "../paths" }
str-util = { path = "../str-util" }
text-size-util = { path = "../text-size-util" }
