[package]
name = "sml-fmt"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[lib]
test = false
doctest = false

[dependencies]
sml-syntax = { path = "../sml-syntax" }
