[package]
name = "sml-parse"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
doctest = false
test = false

[dependencies]
once_cell = "1"
drop_bomb = "0.1"
fast-hash = { path = "../fast-hash" }
str-util = { path = "../str-util" }
sml-syntax = { path = "../sml-syntax" }
