[package]
name = "sml-parse"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
doctest = false
test = false

[dependencies]
event-parse = { git = "https://github.com/azdavis/language-util.git" }
fast-hash = { path = "../fast-hash" }
once_cell = "1"
sml-syntax = { path = "../sml-syntax" }
str-util = { path = "../str-util" }
