[package]
name = "base"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
intern = { path = "../intern" }
token = { path = "../token" }
util = { path = "../util" }
loc = { path = "../loc" }
