[package]
name = "lex"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
doctest = false
test = false

[dependencies]
block-comment = { path = "../block-comment" }
syntax = { path = "../syntax" }
