[package]
name = "millet-ls"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
crossbeam-channel = "0.4"
lsp-types = "0.74"
millet-core = { path = "../core" }
serde = "1.0"
serde_json = "1.0"
