[package]
name = "parse"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
doctest = false
test = false

[dependencies]
once_cell = "1"
drop_bomb = "0.1"
fast-hash = { path = "../fast-hash" }
syntax = { path = "../syntax" }
