[package]
name = "parse-old"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
ast = { path = "../ast" }
intern = { path = "../intern" }
lex-old = { path = "../lex-old" }
loc = { path = "../loc" }
token = { path = "../token" }
