name: ci
on: [push]
env:
  CARGO_INCREMENTAL: 0
  CI: 1
  RUST_BACKTRACE: short
  RUSTFLAGS: "-D warnings"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Set up rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rustfmt, clippy
      - name: Run tests
        run: cargo xtask ci
  dist:
    needs: test
    if: success() && startsWith(github.ref, 'refs/tags/v')
    strategy:
      matrix:
        include:
          - os: windows-latest
            rust: x86_64-pc-windows-msvc
            vscode: win32-x64
          - os: windows-latest
            rust: aarch64-pc-windows-msvc
            vscode: win32-arm64
          - os: ubuntu-latest
            rust: x86_64-unknown-linux-gnu
            vscode: linux-x64
          - os: ubuntu-latest
            rust: aarch64-unknown-linux-gnu
            vscode: linux-arm64
          - os: macos-latest
            rust: x86_64-apple-darwin
            vscode: darwin-x64
          - os: macos-latest
            rust: aarch64-apple-darwin
            vscode: darwin-arm64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Fix git line endings (necessary for windows)
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Set up rust
        uses: actions-rs/toolchain@v1
        with:
          target: ${{ matrix.rust }}
          toolchain: stable
          profile: minimal
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Make dist
        run: cargo xtask dist --release
      - name: Package vsix
        run: npx --no-install vsce package --target ${{ matrix.vscode }} -o millet-${{ matrix.vscode }}.vsix
        working-directory: editors/vscode
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: editors/vscode/millet-${{ matrix.vscode }}.vsix
  release:
    runs-on: ubuntu-latest
    needs: dist
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install node dependencies
        run: npm ci
        working-directory: editors/vscode
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: editors/vscode/dist
      - name: Publish artifacts
        run: npx --no-install vsce publish --pat ${{ secrets.AZURE_MARKETPLACE_TOKEN }} --packagePath dist/*
        working-directory: editors/vscode
